apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jh86
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jh86
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jh86
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jh86
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jh86
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-diyw-tenant/rhtap-demo-app/hacbs-test-project-jh86@sha256:53c7e707d53ee992547163f6b74b27fc39cfb9f545d9d08f1dc06673dfae116e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
